import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Header } from '@/components/layout/Header'
import { Banner } from '@/components/layout/Banner'
import Box from '@/theme/Box'
import { WhoWeAre } from '@/components/layout/WhoWeAre'
import { Technologies } from '@/components/layout/Technologies'
import { CaseStudies } from '@/components/layout/CaseStudies'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Box variant="main" as="main">
        <Banner />
        <WhoWeAre />
        <Technologies />
        <CaseStudies />
      </Box>
    </>
  )
}
